# This file defines all needed services for the local development environment.
# There is another file docker-compose.ci.yml which gets used when running the CI in GitLab.
# If you add any service please also adjust the docker-compose.ci.yml.

version: "3"

networks:
    locl: {}

services:
    mysql:
        image: mariadb:10.3
        networks:
            - locl
        volumes:
            - database:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks:
            - locl
        ports:
            - "8079:80"
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql

    wordpress:
        image: wordpress:5.2.0-apache
        networks:
            - locl
        volumes:
            - www:/var/www/html
            - ../../:/var/www/html/wp-content/plugins/wp-reactjs-starter
            - ../scripts:/scripts
        ports:
            - "80:80"
        restart: on-failure
        depends_on:
            - mysql
        command: bash /scripts/container-wordpress-command.sh
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            # If you adjust username / password you also have to change username / password in ../scripts/e2e-tests-autologin-plugin.php
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress

    wordpress-cli:
        image: wordpress:cli
        user: xfs
        networks:
            - locl
        volumes:
            - www:/var/www/html
            - ../scripts:/scripts
        entrypoint: /scripts/container-wordpress-cli-entrypoint.sh
        depends_on:
            - mysql
            - wordpress

volumes:
    database: {}
    www: {}
